name: bot

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/spaceporn-dep_ubuntu-24.04:zig-0.12.0-dev.3630.215de3ee6
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
    steps:
    - uses: tiawl/spaceporn-dep-action-bot@v1
